version: '3'

services:
  app:
    build: .

  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${URL}
      - MONGO_INITDB_ROOT_PASSWORD=password

    volumes:
      - ./mongo-db:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb

    restart: unless-stopped
    depends_on:
      - mongodb

volumes:
  mongo-db:
